hospitalK/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :tipo_consultorios
  resources :pacientes
  resources :medicos
  resources :tipo_medicos

end

hospitalK/app/models/medico.rb
class Medico < ActiveRecord::Base
  belongs_to :tipo_medico

  validates :nombres,        presence: true
  validates :apellidos,      presence: true
  validates :documento,      presence: true
  validates :documento,      presence: true
  validates :celular,        presence: true
  validates :tipo_medico_id, presence: true
end

hospitalK/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
    @tipos_medico = TipoMedico.all
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nombres, :apellidos, :documento, :celular, :tipo_medico_id)
    end
end

hospitalK/app/helpers/medicos_helper.rb
module MedicosHelper
end

hospitalK/app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :documento %><br>
    <%= f.number_field :documento %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :tipo_medico_id %><br>
    <select class="select" name="medico[tipo_medico_id]">
        <option value=""> Seleccione... </option>
        <% @tipos_medico.each do |tipo_medico| %>
          <option value="<%= tipo_medico.id %>">
            <%= tipo_medico.nombre %>
          </option>
        <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hospitalK/app/views/medicos/edit.html.erb
<h1>Editing Medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

hospitalK/app/views/medicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Medicos</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Documento</th>
      <th>Celular</th>
      <th>Tipo medico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nombres %></td>
        <td><%= medico.apellidos %></td>
        <td><%= medico.documento %></td>
        <td><%= medico.celular %></td>
        <td><%= medico.tipo_medico.nombre %></td>
        <td><%= link_to 'Show', medico %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Medico', new_medico_path %>

hospitalK/app/views/medicos/new.html.erb
<h1>Nuevo Medico</h1>

<%= render 'form' %>

<%= link_to 'Back', medicos_path %>

hospitalK/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @medico.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @medico.apellidos %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @medico.documento %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @medico.celular %>
</p>

<p>
  <strong>Tipo medico:</strong>
  <%= @medico.tipo_medico.nombre %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>