hospitalK/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :tipo_consultorios
  resources :pacientes
  resources :medicos
  resources :tipo_medicos

end

hospitalK/app/models/tipo_medico.rb
class TipoMedico < ActiveRecord::Base
end

hospitalK/app/controllers/tipo_medicos_controller.rb
class TipoMedicosController < ApplicationController
  before_action :set_tipo_medico, only: [:show, :edit, :update, :destroy]

  # GET /tipo_medicos
  # GET /tipo_medicos.json
  def index
    @tipo_medicos = TipoMedico.all
  end

  # GET /tipo_medicos/1
  # GET /tipo_medicos/1.json
  def show
  end

  # GET /tipo_medicos/new
  def new
    @tipo_medico = TipoMedico.new
  end

  # GET /tipo_medicos/1/edit
  def edit
  end

  # POST /tipo_medicos
  # POST /tipo_medicos.json
  def create
    @tipo_medico = TipoMedico.new(tipo_medico_params)

    respond_to do |format|
      if @tipo_medico.save
        format.html { redirect_to @tipo_medico, notice: 'Tipo medico was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_medico }
      else
        format.html { render :new }
        format.json { render json: @tipo_medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_medicos/1
  # PATCH/PUT /tipo_medicos/1.json
  def update
    respond_to do |format|
      if @tipo_medico.update(tipo_medico_params)
        format.html { redirect_to @tipo_medico, notice: 'Tipo medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_medico }
      else
        format.html { render :edit }
        format.json { render json: @tipo_medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_medicos/1
  # DELETE /tipo_medicos/1.json
  def destroy
    @tipo_medico.destroy
    respond_to do |format|
      format.html { redirect_to tipo_medicos_url, notice: 'Tipo medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_medico
      @tipo_medico = TipoMedico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_medico_params
      params.require(:tipo_medico).permit(:nombre)
    end
end

hospitalK/app/helpers/tipo_medicos_helper.rb
module TipoMedicosHelper
end

hospitalK/app/views/tipo_medicos/_form.html.erb
<%= form_for(@tipo_medico) do |f| %>
  <% if @tipo_medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_medico.errors.count, "error") %> prohibited this tipo_medico from being saved:</h2>

      <ul>
      <% @tipo_medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hospitalK/app/views/tipo_medicos/edit.html.erb
<h1>Editing Tipo Medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_medico %> |
<%= link_to 'Back', tipo_medicos_path %>

hospitalK/app/views/tipo_medicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Tipo Medicos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_medicos.each do |tipo_medico| %>
      <tr>
        <td><%= tipo_medico.nombre %></td>
        <td><%= link_to 'Show', tipo_medico %></td>
        <td><%= link_to 'Edit', edit_tipo_medico_path(tipo_medico) %></td>
        <td><%= link_to 'Destroy', tipo_medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tipo medico', new_tipo_medico_path %>

hospitalK/app/views/tipo_medicos/new.html.erb
<h1>Nuevo Tipo Medico</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_medicos_path %>

hospitalK/app/views/tipo_medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_medico.nombre %>
</p>

<%= link_to 'Edit', edit_tipo_medico_path(@tipo_medico) %> |
<%= link_to 'Back', tipo_medicos_path %>