hospitalK/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :tipo_consultorios
  resources :pacientes
  resources :medicos
  resources :tipo_medicos

end

hospitalK/app/models/paciente.rb
class Paciente < ActiveRecord::Base
    validates :nombres,          presence: true
    validates :apellidos,        presence: true
    validates :documento,        presence: true
    validates :fecha_nacimiento, presence: true
end

hospitalK/app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nombres, :apellidos, :fecha_nacimiento, :documento)
    end
end

hospitalK/app/helpers/pacientes_helper.rb
module PacientesHelper
end

hospitalK/app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %><br>
    <%= f.date_select :fecha_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :documento %><br>
    <%= f.number_field :documento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hospitalK/app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

hospitalK/app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Fecha nacimiento</th>
      <th>Documento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nombres %></td>
        <td><%= paciente.apellidos %></td>
        <td><%= paciente.fecha_nacimiento %></td>
        <td><%= paciente.documento %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Paciente', new_paciente_path %>

hospitalK/app/views/pacientes/new.html.erb
<h1>Nuevo Paciente</h1>

<%= render 'form' %>

<%= link_to 'Back', pacientes_path %>

hospitalK/app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @paciente.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @paciente.apellidos %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @paciente.fecha_nacimiento %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @paciente.documento %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>