hospitalK/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :tipo_consultorios
  resources :pacientes
  resources :medicos
  resources :tipo_medicos

end

hospitalK/app/models/tipo_consultorio.rb
class TipoConsultorio < ActiveRecord::Base
end

hospitalK/app/controllers/tipo_consultorios_controller.rb
class TipoConsultoriosController < ApplicationController
  before_action :set_tipo_consultorio, only: [:show, :edit, :update, :destroy]

  # GET /tipo_consultorios
  # GET /tipo_consultorios.json
  def index
    @tipo_consultorios = TipoConsultorio.all
  end

  # GET /tipo_consultorios/1
  # GET /tipo_consultorios/1.json
  def show
  end

  # GET /tipo_consultorios/new
  def new
    @tipo_consultorio = TipoConsultorio.new
  end

  # GET /tipo_consultorios/1/edit
  def edit
  end

  # POST /tipo_consultorios
  # POST /tipo_consultorios.json
  def create
    @tipo_consultorio = TipoConsultorio.new(tipo_consultorio_params)

    respond_to do |format|
      if @tipo_consultorio.save
        format.html { redirect_to @tipo_consultorio, notice: 'Tipo consultorio was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_consultorio }
      else
        format.html { render :new }
        format.json { render json: @tipo_consultorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_consultorios/1
  # PATCH/PUT /tipo_consultorios/1.json
  def update
    respond_to do |format|
      if @tipo_consultorio.update(tipo_consultorio_params)
        format.html { redirect_to @tipo_consultorio, notice: 'Tipo consultorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_consultorio }
      else
        format.html { render :edit }
        format.json { render json: @tipo_consultorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_consultorios/1
  # DELETE /tipo_consultorios/1.json
  def destroy
    @tipo_consultorio.destroy
    respond_to do |format|
      format.html { redirect_to tipo_consultorios_url, notice: 'Tipo consultorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_consultorio
      @tipo_consultorio = TipoConsultorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_consultorio_params
      params.require(:tipo_consultorio).permit(:nombre)
    end
end

hospitalK/app/helpers/tipo_consultorios_helper.rb
module TipoConsultoriosHelper
end

hospitalK/app/views/tipo_consultorios/_form.html.erb
<%= form_for(@tipo_consultorio) do |f| %>
  <% if @tipo_consultorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_consultorio.errors.count, "error") %> prohibited this tipo_consultorio from being saved:</h2>

      <ul>
      <% @tipo_consultorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hospitalK/app/views/tipo_consultorios/edit.html.erb
<h1>Editing Tipo Consultorio</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_consultorio %> |
<%= link_to 'Back', tipo_consultorios_path %>

hospitalK/app/views/tipo_consultorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Tipo Consultorios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_consultorios.each do |tipo_consultorio| %>
      <tr>
        <td><%= tipo_consultorio.nombre %></td>
        <td><%= link_to 'Show', tipo_consultorio %></td>
        <td><%= link_to 'Edit', edit_tipo_consultorio_path(tipo_consultorio) %></td>
        <td><%= link_to 'Destroy', tipo_consultorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tipo consultorio', new_tipo_consultorio_path %>

hospitalK/app/views/tipo_consultorios/new.html.erb
<h1>Nuevo Tipo Consultorio</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_consultorios_path %>

hospitalK/app/views/tipo_consultorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_consultorio.nombre %>
</p>

<%= link_to 'Edit', edit_tipo_consultorio_path(@tipo_consultorio) %> |
<%= link_to 'Back', tipo_consultorios_path %>